// Curated Bollywood surprises — memes, dialogues, songs & iconic moments
// Organised by vibe. Each surprise is a hidden "gift" inside a postcard.

export type Vibe = "jolly" | "romantic" | "action" | "classic";

export type SurpriseType = "meme" | "dialogue" | "song" | "moment";

export interface Surprise {
  id: string;
  vibe: Vibe;
  type: SurpriseType;
  title: string;
  character: string;
  movie?: string;
  quote: string;
  caption: string;
  emoji: string;
  gifUrl?: string;
  accent: string; // tailwind-ish hex for card accent
}

export interface VibeMeta {
  id: Vibe;
  label: string;
  emoji: string;
  tagline: string;
  description: string;
}

export const VIBES: VibeMeta[] = [
  {
    id: "jolly",
    label: "Jolly",
    emoji: "😂",
    tagline: "Haste haste bhej do",
    description: "Comic legends & timeless one-liners to crack them up.",
  },
  {
    id: "romantic",
    label: "Romantic",
    emoji: "❤️",
    tagline: "Dil se dil tak",
    description: "Soulful songs & dialogues that say what words can't.",
  },
  {
    id: "action",
    label: "Action Hero",
    emoji: "🔥",
    tagline: "Entry full swag",
    description: "Swag entries & power-packed moments for the hero mode.",
  },
  {
    id: "classic",
    label: "Classic",
    emoji: "✨",
    tagline: "Puraani yaadein",
    description: "A timeless mix — let the postcard choose the mood.",
  },
];

export const SURPRISES: Surprise[] = [
  // ============ 😂 JOLLY — Johnny Lever, Akshay Kumar, Javed Jaffrey ============
  {
    id: "jl-amaza-ayega",
    vibe: "jolly",
    type: "dialogue",
    title: "Abhi Maza Aayega",
    character: "Johnny Lever",
    movie: " Johnny Lever Special",
    quote: "Abhi maza aayega na bhidu... abhi toh shuru hua hai!",
    caption: "The suspense was worth it, bhidu.",
    emoji: "🤣",
    accent: "#d97706",
  },
  {
    id: "jl-chhota-chhatri",
    vibe: "jolly",
    type: "dialogue",
    title: "Ayee Chhota Chhatri",
    character: "Johnny Lever",
    quote: "Aye chhota chhatri! Kya kar raha hai tu idhar?",
    caption: "Surprise open karo, chhota chhatri!",
    emoji: "🎩",
    accent: "#b45309",
  },
  {
    id: "jl-thik-karke",
    vibe: "jolly",
    type: "dialogue",
    title: "Abhi Thik Karke Deta Hu",
    character: "Johnny Lever",
    quote: "Abhi thik karke deta hu... ekdum jaisa pehle tha!",
    caption: "Sending you a fix-it-up smile.",
    emoji: "🔧",
    accent: "#ca8a04",
  },
  {
    id: "jl-holi-hai",
    vibe: "jolly",
    type: "moment",
    title: "Aaj Holi Hai",
    character: "Johnny Lever",
    movie: "Golmaal 3",
    quote: "Aaj holi hai... rang birangi baatein, rang birangi yaadein!",
    caption: "Rang ja, yaaron ka pyaar hai.",
    emoji: "🎨",
    accent: "#db2777",
  },
  {
    id: "jl-guarantee",
    vibe: "jolly",
    type: "dialogue",
    title: "Guarantee Nahi De Sakta",
    character: "Johnny Lever",
    quote: "Iski guarantee main nahi de sakta... par maza zaroor aayega!",
    caption: "No guarantees, only good vibes.",
    emoji: "🤷",
    accent: "#a16207",
  },
  {
    id: "jl-galti-hai",
    vibe: "jolly",
    type: "meme",
    title: "Yeh Bhi Meri Galti Hai",
    character: "Johnny Lever",
    movie: "Johnny Lever Meme",
    quote: "Yeh bhi meri galti hai... yeh bhi meri galti hai!",
    caption: "Mana liya, ab khul ja surprise!",
    emoji: "😅",
    gifUrl: "https://tenor.com/view/yeh-bhi-meri-galti-hai-ye-bhi-meri-galti-hai-johnny-lever-johnny-lever-meme-akhsay-kumar-meme-gif-6818294267016527359",
    accent: "#c2410c",
  },
  {
    id: "ak-link-dena",
    vibe: "jolly",
    type: "meme",
    title: "Ayee Link Dena",
    character: "Akshay Kumar",
    quote: "Ayee link dena... abhi forward karta hu!",
    caption: "Yeh link, dil se bheja hai.",
    emoji: "🔗",
    gifUrl: "https://tenor.com/view/ayee-link-dena-gif-17590636023769861346",
    accent: "#0891b2",
  },
  {
    id: "ak-thanks-kambakht",
    vibe: "jolly",
    type: "dialogue",
    title: "Thanks, Kambakht",
    character: "Akshay Kumar",
    movie: "Kambakkht Ishq",
    quote: "Thanks... kambakht, tu hi toh hai mere paas.",
    caption: "Kambakht, thanks for being you.",
    emoji: "🙏",
    accent: "#be123c",
  },
  {
    id: "ak-behan-dar-gayi",
    vibe: "jolly",
    type: "meme",
    title: "Behan Dar Gayi",
    character: "Akshay Kumar",
    quote: "Behan dar gayi... but tu nahi dar sakta, postcard khol!",
    caption: "Dar mat, yaar hai tu.",
    emoji: "😱",
    accent: "#7c3aed",
  },
  {
    id: "ak-paisa-hi-paisa",
    vibe: "jolly",
    type: "meme",
    title: "Paisa Hi Paisa Hoga",
    character: "Akshay Kumar",
    quote: "Paisa hi paisa hoga... par asli daawat toh pyaar hai!",
    caption: "Pyaar hi paisa hai, bhai.",
    emoji: "💸",
    accent: "#15803d",
  },
  {
    id: "ak-bhai-bhai-soyenge",
    vibe: "jolly",
    type: "moment",
    title: "Bhai Bhai Milke Soyenge",
    character: "Akshay Kumar & Salman Khan",
    movie: "Mujhse Shaadi Karogi",
    quote: "Kabhi tu yahaan so, kabhi main wahaaan... bhai bhai milke soyenge!",
    caption: "Apno ke beech, aaram se.",
    emoji: "🛌",
    gifUrl: "https://tenor.com/view/mujhse-shaadi-karogi-akshay-kumar-salman-khan-kabhi-tu-yaha-so-kabhi-mai-vaha-so-kabhi-ek-dusre-par-soyenge-bhai-bhai-milke-soyenge-gif-17959058",
    accent: "#1d4ed8",
  },
  {
    id: "jj-udi-baba",
    vibe: "jolly",
    type: "meme",
    title: "Udi Baba Udi Baba",
    character: "Javed Jaffrey",
    movie: "Dhamaal",
    quote: "Chalti toh hai nahi... udi baba, udi baba!",
    caption: "Surprise udi baba, pakad lo!",
    emoji: "✈️",
    gifUrl: "https://tenor.com/view/dhamaal-javed-jaffrey-chalti-toh-hai-nahi-udi-baba-udi-baba-gif-18173495",
    accent: "#0369a1",
  },
  {
    id: "jj-kitne-paise",
    vibe: "jolly",
    type: "dialogue",
    title: "Kitne Paise Huey",
    character: "Javed Jaffrey",
    movie: "Dhamaal",
    quote: "Uss hisaab se mere kitne paise huey?",
    caption: "Pyaar ka hisaab, full paisa vasool.",
    emoji: "🧮",
    gifUrl: "https://tenor.com/view/uss-hisaab-se-mere-kitne-paise-huey-manav-dhamaal-javed-jaffrey-gif-10572523281542780289",
    accent: "#0f766e",
  },
  {
    id: "jj-not-so-smart",
    vibe: "jolly",
    type: "meme",
    title: "He Is Not So Smart",
    character: "Javed Jaffrey",
    movie: "Dhamaal",
    quote: "Adi... he is not so smart. He's not so smart!",
    caption: "Smart nahi, dil se smart hai.",
    emoji: "🤓",
    gifUrl: "https://tenor.com/view/dhamaal-javed-jaffrey-adi-he-is-not-so-smart-hes-not-so-smart-gif-18173312",
    accent: "#475569",
  },
  {
    id: "jj-aage-aise",
    vibe: "jolly",
    type: "dialogue",
    title: "Aise Mein Aage Kaise",
    character: "Javed Jaffrey",
    movie: "Dhamaal",
    quote: "Paya nahi... aisi dangerous situations mein main automatically aage kaise aa jaata hoon!",
    caption: "Aage aana padega, surprise yahi hai.",
    emoji: "🏃",
    gifUrl: "https://tenor.com/view/dhamaal-javed-jaffrey-paya-nahi-aisi-dangerous-situations-mein-mai-automatically-aage-kaise-aa-jata-hoon-gif-18173401",
    accent: "#9f1239",
  },

  // ============ 🔥 ACTION HERO — Salman Khan, Hrithik Roshan ============
  {
    id: "sk-commitment",
    vibe: "action",
    type: "dialogue",
    title: "Ek Baar Commitment",
    character: "Salman Khan",
    movie: "Wanted",
    quote: "Ek baar jo maine commitment kar di... uske baad apne aap ki bhi nahi sunta!",
    caption: "Commitment kar di — yeh postcard tere liye.",
    emoji: "💪",
    gifUrl: "https://tenor.com/view/ek-baar-jo-maine-commitment-kardi-uske-baad-apne-aap-kibhi-nahi-sunta-gif-7769208924808356520",
    accent: "#1e293b",
  },
  {
    id: "sk-oh-yes-handsome",
    vibe: "action",
    type: "moment",
    title: "Oh Yes, Handsome!",
    character: "Salman Khan",
    quote: "Oh yes... handsome, ready ho ja surprise ke liye!",
    caption: "Handome entry, handsome surprise.",
    emoji: "😎",
    gifUrl: "https://tenor.com/view/oh-yes-handsome-sunglasses-gif-15760305",
    accent: "#334155",
  },
  {
    id: "sk-salman-entry",
    vibe: "action",
    type: "moment",
    title: "Bhai Ki Entry",
    character: "Salman Khan",
    quote: "Bhai aagaye... ab aur kya chahiye?",
    caption: "Bhai ka pyaar, tere liye.",
    emoji: "🕶️",
    gifUrl: "https://tenor.com/view/salman-khan-gif-14971439",
    accent: "#0c4a6e",
  },
  {
    id: "sk-namaste",
    vibe: "action",
    type: "moment",
    title: "Namaste, Celebration",
    character: "Salman Khan",
    quote: "Namaste... haath jod ke bheja hai yeh postcard!",
    caption: "Haath jod ke, dil se.",
    emoji: "🤝",
    gifUrl: "https://tenor.com/view/holding-hands-namaste-heroes-salman-khan-celebration-gif-744390825087103431",
    accent: "#7c2d12",
  },
  {
    id: "sk-dabangg-love",
    vibe: "action",
    type: "moment",
    title: "Dabangg Love",
    character: "Salman Khan",
    movie: "Dabangg",
    quote: "Cool glasses, cool kulfy... aur tere liye cool postcard!",
    caption: "Dabangg style mein, yaad bheji.",
    emoji: "🦸",
    gifUrl: "https://tenor.com/view/salman-khan-love-dabangg-glasses-kulfy-gif-5530577291219038577",
    accent: "#7f1d1d",
  },
  {
    id: "hr-war-entry",
    vibe: "action",
    type: "moment",
    title: "Hotness Alert — War",
    character: "Hrithik Roshan",
    movie: "War",
    quote: "Entry ho gayi... hotness alert, surprise bhi aagaya!",
    caption: "Style se khula surprise.",
    emoji: "🔥",
    gifUrl: "https://tenor.com/view/war-hrithik-roshan-hrithik-style-hrithik-entry-hotness-alert-gif-19873739",
    accent: "#b91c1c",
  },
  {
    id: "hr-plan-kya",
    vibe: "action",
    type: "dialogue",
    title: "Plan Kya Hai?",
    character: "Hrithik Roshan",
    quote: "Plan kya hai tumhara? Postcard khol aur dekh!",
    caption: "Plan: surprise khul gaya.",
    emoji: "📋",
    gifUrl: "https://tenor.com/view/plan-what's-your-plan-plan-kya-plan-kya-hai-tumhara-goggles-gif-1356955180928040300",
    accent: "#1e40af",
  },
  {
    id: "hr-best",
    vibe: "action",
    type: "moment",
    title: "Simply The Best",
    character: "Hrithik Roshan",
    quote: "Tum ho hi best... toh surprise bhi best hi hoga!",
    caption: "Best, tere liye hi.",
    emoji: "⭐",
    gifUrl: "https://tenor.com/view/best-gif-9019929844728787973",
    accent: "#a16207",
  },

  // ============ ❤️ ROMANTIC — Ranbir Kapoor, Emraan Hashmi ============
  {
    id: "rk-ae-dil-mushkil",
    vibe: "romantic",
    type: "dialogue",
    title: "Ae Dil Hai Mushkil",
    character: "Ranbir Kapoor",
    movie: "Ae Dil Hai Mushkil",
    quote: "Ae dil hai mushkil... par tujhe bhejna asaan hai.",
    caption: "Mushkil se asaan tak, tere liye.",
    emoji: "💔",
    gifUrl: "https://tenor.com/view/ranbir-kapoor-ae-dil-hai-mushkil-senem-hindi-gif-5682658576562307589",
    accent: "#9f1239",
  },
  {
    id: "rk-excited-laddu",
    vibe: "romantic",
    type: "moment",
    title: "Excited Laddu",
    character: "Ranbir Kapoor",
    quote: "Excited? Laddu jaisa meetha surprise aagaya!",
    caption: "Mithaas, tere naam.",
    emoji: "🧡",
    gifUrl: "https://tenor.com/view/ranbir-kapoor-excited-working-happy-laddu-gif-23008047",
    accent: "#ea580c",
  },
  {
    id: "rk-tu-jhoothi-makkaar",
    vibe: "romantic",
    type: "dialogue",
    title: "Tu Jhoothi Main Makkaar",
    character: "Ranbir Kapoor",
    movie: "Tu Jhoothi Main Makkaar",
    quote: "Tu jhoothi, main makkaar... par yeh postcard sach hai!",
    caption: "Sachi yaad, jhoothi confidence nahi.",
    emoji: "💘",
    gifUrl: "https://tenor.com/view/tu-jhoothi-main-makkaar-ranbir-kapoor-shraddha-kapoor-gif-27476430",
    accent: "#be185d",
  },
  {
    id: "rk-brahmastra",
    vibe: "romantic",
    type: "moment",
    title: "Brahmastra — Astra of Love",
    character: "Ranbir Kapoor & Alia Bhatt",
    movie: "Brahmastra",
    quote: "Astra toh bahut hain... par pyaar ka sabse powerful!",
    caption: "Pyaar ka astra, tere liye.",
    emoji: "✨",
    gifUrl: "https://tenor.com/view/brahmastra-brahmastra-trailer-brahmastra-movie-alia-bhatt-ranbir-kapoor-gif-25953382",
    accent: "#6d28d9",
  },
  {
    id: "rk-anushka-moment",
    vibe: "romantic",
    type: "moment",
    title: "Anushka & Ranbir",
    character: "Ranbir Kapoor & Anushka Sharma",
    quote: "Thodi si mushkil, thoda sa pyaar... postcard mein dono!",
    caption: "Mushkil aur pyaar, saath mein.",
    emoji: "💕",
    gifUrl: "https://tenor.com/view/anushka-sharma-ranbir-kapoor-gif-19028729",
    accent: "#db2777",
  },
  {
    id: "rk-ae-dil-all",
    vibe: "romantic",
    type: "moment",
    title: "Ae Dil — The Ensemble",
    character: "Ranbir Kapoor, Aishwarya, Anushka, Fawad",
    movie: "Ae Dil Hai Mushkil",
    quote: "Ae dil... tere liye, sabse khoobsurat surprise.",
    caption: "Khoobsurat, jaise tu.",
    emoji: "🌹",
    gifUrl: "https://tenor.com/view/ranbir-kapoor-aishwarya-rai-anushka-sharma-fawad-khan-ae-dil-hai-mushkil-gif-683228443256261346",
    accent: "#a21caf",
  },
  {
    id: "eh-aye-khuda",
    vibe: "romantic",
    type: "song",
    title: "Aye Khuda",
    character: "Emraan Hashmi",
    movie: "Murder 2",
    quote: "Aye khuda... mujhe yeh postcard pohocha de uss tak.",
    caption: "Aye khuda, sun le yeh dua.",
    emoji: "🌙",
    accent: "#1e3a8a",
  },
  {
    id: "eh-tu-hi-haqeeqat",
    vibe: "romantic",
    type: "song",
    title: "Tu Hi Haqeeqat",
    character: "Emraan Hashmi",
    movie: "Tum Mile",
    quote: "Tu hi haqeeqat... tu hi meri shab hai.",
    caption: "Haqeeqat, tu hi.",
    emoji: "🌠",
    accent: "#312e81",
  },
  {
    id: "eh-tu-hi-meri-shab",
    vibe: "romantic",
    type: "song",
    title: "Tu Hi Meri Shab Hai",
    character: "Emraan Hashmi",
    movie: "Gangster",
    quote: "Tu hi meri shab hai... tu hi mera sab hai.",
    caption: "Meri shab, mera sab.",
    emoji: "🌌",
    accent: "#4c1d95",
  },
  {
    id: "eh-kaho-na-kaho",
    vibe: "romantic",
    type: "song",
    title: "Kaho Na Kaho",
    character: "Emraan Hashmi",
    movie: "Murder",
    quote: "Kaho na kaho... yeh postcard tere liye hai.",
    caption: "Kaho na... keh diya, bhej diya.",
    emoji: "🎵",
    accent: "#831843",
  },
  {
    id: "eh-wonderful-journey",
    vibe: "romantic",
    type: "dialogue",
    title: "A Wonderful Journey",
    character: "Emraan Hashmi",
    quote: "It was a wonderful journey... aur yeh postcard usi ka hissa.",
    caption: "Wonderful journey, ek aur yaad.",
    emoji: "🛤️",
    gifUrl: "https://tenor.com/view/it-was-a-wonderful-journey-emraan-hashmi-pinkvilla-it-was-fun-i-had-a-wonderful-time-gif-1362834078848933966",
    accent: "#155e75",
  },
  {
    id: "eh-once-upon-mumbai",
    vibe: "romantic",
    type: "moment",
    title: "Once Upon A Time In Mumbai",
    character: "Emraan Hashmi & Prachi Desai",
    movie: "Once Upon A Time In Mumbai",
    quote: "Once upon a time... ek postcard, ek yaad, ek tu.",
    caption: "Puraani Mumbai, nayi yaad.",
    emoji: "🏙️",
    gifUrl: "https://tenor.com/view/bollywood-once-upon-a-time-in-mumbai-emraan-hashmi-prachi-desai-nimra-gif-7564422617388680183",
    accent: "#92400e",
  },

  // ============ ✨ CLASSIC — a timeless mix (default vibe) ============
  {
    id: "cl-timeless",
    vibe: "classic",
    type: "dialogue",
    title: "Puraani Yaad",
    character: "A Nostalgic Memory",
    quote: "Kuch baatein, kuch lamhe... waqt ke saath, dil ke paas.",
    caption: "Waqt gaya, yaad reh gayi.",
    emoji: "🕰️",
    accent: "#78716c",
  },
  {
    id: "cl-letter",
    vibe: "classic",
    type: "dialogue",
    title: "Chitthi",
    character: "A Nostalgic Memory",
    quote: "Chitthi aayi hai... dil se likhi, dil tak pohochi.",
    caption: "Chitthi, tere naam.",
    emoji: "✉️",
    accent: "#a16207",
  },
  {
    id: "cl-rain",
    vibe: "classic",
    type: "moment",
    title: "Baarish Ki Yaad",
    character: "A Nostalgic Memory",
    quote: "Baarish ki bundon mein, ek puraani si baat... tere saath.",
    caption: "Baarish aur tu, humesha.",
    emoji: "🌧️",
    accent: "#475569",
  },
  {
    id: "cl-tea",
    vibe: "classic",
    type: "moment",
    title: "Ek Cup Chai",
    character: "A Nostalgic Memory",
    quote: "Ek cup chai, ek puraana gaana... aur tu, yaadon mein.",
    caption: "Chai aur charcha, bina tere.",
    emoji: "☕",
    accent: "#854d0e",
  },
  {
    id: "cl-train",
    vibe: "classic",
    type: "moment",
    title: "Train Ki Siti",
    character: "A Nostalgic Memory",
    quote: "Train ki siti... aur platform pe ek haath, hilta rehta hai.",
    caption: "Milte rahi, chitthi aati rahi.",
    emoji: "🚂",
    accent: "#52525b",
  },
];

export function getSurprisesForVibe(vibe: Vibe): Surprise[] {
  if (vibe === "classic") {
    // Classic mixes a sampling across all vibes for variety
    const pool = [
      "jl-amaza-ayega",
      "ak-link-dena",
      "sk-commitment",
      "hr-war-entry",
      "rk-ae-dil-mushkil",
      "eh-tu-hi-meri-shab",
      "cl-timeless",
      "cl-chitthi",
    ];
    return SURPRISES.filter((s) => pool.includes(s.id));
  }
  return SURPRISES.filter((s) => s.vibe === vibe);
}

export function getSurpriseById(id: string): Surprise | undefined {
  return SURPRISES.find((s) => s.id === id);
}

export function getVibeMeta(vibe: Vibe): VibeMeta {
  return VIBES.find((v) => v.id === vibe) ?? VIBES[3];
}
